export const adData = [
  {
    id: 1,
    title: "Appartement lumineux avec balcon",
    price: "185 000 €",
    location: "Paris 15ème, Île-de-France",
    features: "2 chambres • 65 m² • 3ème étage",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 2,
    title: "Maison de campagne rénovée",
    price: "320 000 €",
    location: "Aix-en-Provence, PACA",
    features: "4 chambres • 120 m² • Jardin",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 3,
    title: "Studio au cœur de la ville",
    price: "98 000 €",
    location: "Lyon 2ème, Rhône-Alpes",
    features: "1 pièce • 30 m² • Meublé",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 4,
    title: "Loft industriel avec terrasse",
    price: "275 000 €",
    location: "Bordeaux, Nouvelle-Aquitaine",
    features: "2 chambres • 85 m² • Terrasse 15 m²",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 5,
    title: "Villa avec piscine",
    price: "495 000 €",
    location: "Montpellier, Occitanie",
    features: "5 chambres • 180 m² • Piscine",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 6,
    title: "Appartement rénové proche métro",
    price: "210 000 €",
    location: "Toulouse, Occitanie",
    features: "3 chambres • 72 m² • Parking",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 7,
    title: "Maison de ville avec cour",
    price: "245 000 €",
    location: "Nantes, Pays de la Loire",
    features: "3 chambres • 95 m² • Cour privée",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 8,
    title: "Duplex avec vue panoramique",
    price: "365 000 €",
    location: "Nice, PACA",
    features: "3 chambres • 110 m² • Vue mer",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 9,
    title: "Chalet en montagne",
    price: "420 000 €",
    location: "Chamonix, Auvergne-Rhône-Alpes",
    features: "4 chambres • 140 m² • Cheminée",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 10,
    title: "Appartement haussmannien",
    price: "580 000 €",
    location: "Paris 8ème, Île-de-France",
    features: "3 chambres • 105 m² • Parquet",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 11,
    title: "Maison contemporaine",
    price: "395 000 €",
    location: "Rennes, Bretagne",
    features: "4 chambres • 130 m² • Domotique",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 12,
    title: "Studio étudiant rénové",
    price: "89 000 €",
    location: "Lille, Hauts-de-France",
    features: "1 pièce • 25 m² • Proche campus",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 13,
    title: "Ferme à rénover",
    price: "220 000 €",
    location: "Dijon, Bourgogne-Franche-Comté",
    features: "3 chambres • 160 m² • Terrain 2000 m²",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 14,
    title: "Appartement avec cave",
    price: "165 000 €",
    location: "Strasbourg, Grand Est",
    features: "2 chambres • 68 m² • Cave",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 15,
    title: "Maison de village en pierre",
    price: "198 000 €",
    location: "Avignon, PACA",
    features: "3 chambres • 90 m² • Cour intérieure",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
];
